# -*- coding: utf-8 -*-
"""SpeechBrainTests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hVGvvWXYIRSwnY6NHleCysC4bIUGpq2e
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q torchaudio==0.10.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html
# %pip install speechbrain
# %pip install transformers

!git clone https://github.com/speechbrain/speechbrain/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/speechbrain
!pip install -r requirements.txt
!pip install --editable .

from speechbrain.dataio.dataio import read_audio
from IPython.display import Audio

from speechbrain.pretrained import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-commonvoice-fr", savedir="pretrained_models/asr-crdnn-commonvoice-fr")
asr_model.transcribe_file("speechbrain/asr-crdnn-commonvoice-fr/test3.mp3")

#signal = read_audio("Voix005.wav").squeeze()
#Audio(signal, rate = 1)
Audio(filename = "test3.mp3", rate = 50000)